day7/urls.py
from django.urls import path
from . import views
app_name = "day7"

urlpatterns = [
   path('', views.index, name='index'),
   path('accounts/login/', views.login_view, name='login_view'),
   path('logout_view/', views.logout_view, name='logout_view'),
   path('update_task/<int:task_id>/', views.update_task, name='update_task'),
   path('delete_task/<int:task_id>/', views.delete_task, name='delete_task'),
   path('order_by_date/', views.order_by_date, name='order_by_date'),
   path('search/', views.search, name='search'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('day7.urls')),
]

day7/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    status_choices = [
        ('NI','Not Started'),
        ('IP','In Progress'),
        ('CM','Completed'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="tasks")
    title = models.CharField(max_length=100)
    desc = models.TextField()
    deadline = models.DateField(auto_now_add=False)
    status = models.CharField(choices = status_choices, max_length=2, default="NI" )


    def __str__(self):
        return self.title
    

day7/forms.py
from django import forms
from .models import Task

from django.contrib.auth.forms import AuthenticationForm

class LoginForm(AuthenticationForm):
    username = forms.CharField(label='Username', max_length=30, widget=forms.TextInput(attrs={'autofocus': True}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput)




class AddTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title','desc','deadline']

        
class UpdateTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title','desc','deadline', 'status']

day7/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required,  permission_required
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
# from django.views.decorators.http import require_POST

from . import forms

from . import models
# Create your views here.
@login_required
def index(request):

    tasks = models.Task.objects.filter(user=request.user)


    if request.method=="POST":
        add_task_form_data = forms.AddTaskForm(data=request.POST)
        # print(add_task_form_data)
        if add_task_form_data.is_valid():
            print(type(add_task_form_data.cleaned_data))
            
            # add_task_form_data.cleaned_data['user'] = request.user
            # add_task_form_data.save()
            # print(add_task_form_data.cleaned_data)
            cleaned_data = add_task_form_data.cleaned_data

            task_title = cleaned_data.get('title')
            task_desc = cleaned_data.get('desc')
            task_deadline = cleaned_data.get('deadline')
            task_user = request.user

            models.Task.objects.create(
                user = task_user,
                title = task_title,
                desc = task_desc,
                deadline = task_deadline
            )

        

            return redirect("day7:index")

        else:
            return HttpResponse("Invalid Form Data")


    else:
        context = {
            'user':request.user,
            'add_task_form':forms.AddTaskForm,
            'tasks':tasks[::-1],


        }
        return render(request, 'day7/index.html', context)


  


def login_view(request):
    if request.method == 'POST':
        form = forms.LoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('day7:index')
    else:
        form = forms.LoginForm()
    return render(request, 'day7/login.html', {'login_form': form})


def logout_view(request):
    logout(request)
    return redirect('day7:login_view')


def update_task(request, task_id):

    if request.method=="POST":
        add_task_form_data = forms.UpdateTaskForm(data=request.POST)
        if add_task_form_data.is_valid():
            cleaned_data = add_task_form_data.cleaned_data
            task = models.Task.objects.get(id=task_id)
            task.title = cleaned_data.get('title')
            task.desc = cleaned_data.get('desc')
            task.deadline = cleaned_data.get('deadline')
            task.status = cleaned_data.get('status')
            task.save()
            return redirect('day7:index')
        else:
            return HttpResponse("Invalid Form Data")
    else:
        task = models.Task.objects.get(id=task_id)

        context = {
        
            'add_task_form':forms.UpdateTaskForm(instance=task),

        }
        return render(request, 'day7/update.html', context)




def delete_task(request, task_id):
    task = models.Task.objects.get(id=task_id)
    task.delete()
    return redirect('day7:index')



def order_by_date(request):
    tasks = models.Task.objects.filter(user=request.user).order_by('deadline')

    context = {
        'tasks':tasks,
        'user':request.user,
        'add_task_form':forms.AddTaskForm,
    }
    return render(request,'day7/index.html', context)



def search(request):
    search_text = request.GET.get('search_text')
    tasks = models.Task.objects.filter(title__icontains=search_text)
    context = {
        'tasks':tasks,
        'user':request.user,
        'add_task_form':forms.AddTaskForm,
    }
    return render(request,'day7/index.html', context)

day7/templates/day7/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}

      {% endblock %}
    </title>
    {% block links %}
    {% endblock %}
  </head>

  <body>
    {% block content %}

    {% endblock %}
  </body>
</html>

day7/templates/day7/index.html
{% extends 'day7/base.html' %} {% load static %} {% block title %} Task Manager {% endblock %} {% block links %}
<link rel="stylesheet" href="{% static 'day7/css/index.css' %}" /> {% endblock %} {% block content %} <nav>
    <h1>Welcome , {{ user.username|capfirst }}</h1>
    <a href="{% url 'day7:logout_view' %}" >Logout</a>
</nav>
<main>
    <div class="add-task">
        <h3>Add Task</h3>
        <form action="" method="post"> {% csrf_token %} {{ add_task_form.as_ul }} <li class="button">
                <input type="submit" value="Add Task" />
            </li>
        </form>
    </div>
    <div class="tasks">
        <h1>Tasks</h1>
        <a href="{% url 'day7:order_by_date' %}">Order by deadline</a>
        <form action="/search">
            <input type="text" name="search_text">
            <input type="submit" value="Search">
            
        </form>
        <hr> {% if tasks %} {% for task in tasks %} <div class="task">
            <h2>{{ task.title }}</h2>
            <p>{{ task.desc }}</p>
            <p>Task Deadline : {{ task.deadline }}</p>
            <p>Task Status : {{ task.get_status_display }}</p>
            <a href="{% url 'day7:update_task' task.id  %}">Update</a>
            <a href="{% url 'day7:delete_task' task.id  %}">Delete</a>
        </div> {% endfor %} {% else %} There are no any tasks currently {% endif %}
    </div>
</main> {% endblock %}

day7/templates/day7/login.html
{% extends 'day7/base.html' %}
{% load static %}
{% block title %}
  Login Page
{% endblock %}
{% block links %}
  <link rel="stylesheet" href="{% static 'day7/css/login_form.css' %}" />
{% endblock %}
{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    {{ login_form.as_ul }}
    <li class="button">
      <input type="submit" value="Login" />
    </li>

    {% if error_message %}
      {{ error_message }}
    {% endif %}
  </form>
{% endblock %}

day7/templates/day7/update.html
{% extends "day7/base.html" %}
{% load static %}
{% block links %}
<link rel="stylesheet" href="{% static 'day7/css/index.css' %}" />

{% endblock links %}

{% block content %}
<main>
    <div class="add-task">
      <h3>Update Task</h3>
      <form action="" method="post">
        {% csrf_token %}
        {{ add_task_form.as_ul }}
        <li class="button">
          <input type="submit" value="Update Task" />
        </li>
      </form>
    </div>
   
  </main>
{% endblock content %}